name: Build and Publish ISO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v24

      - name: Build ISO
        id: build_iso
        run: |
          nix build

      - name: Create a tarball of directory
        run: |
          tar -czf iso-bundle.tar.gz result/*

      - name: Upload ISO artifact
        if: steps.compare_hash.outputs.changed == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: iso-bundle
          path: iso-bundle.tar.gz

      - name: Commit updated hash
        if: steps.compare_hash.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/iso.hash
          git commit -m "Update ISO hash after successful build"
          git push origin main
