name: Nix PR Checks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Check NixOS configuration
        run: |
          set -euo pipefail
          if ! nix flake check | tee flake-check.log; then
            echo "::error file=flake.nix, title=Flake check failed::nix flake check failed! See logs above."
            exit 1
          fi

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install linting tools
        run: |
          nix profile install \
            nixpkgs#nixpkgs-fmt \
            nixpkgs#statix \
            nixpkgs#deadnix

      - name: Check formatting
        run: |
          nixpkgs-fmt --check .

      - name: Lint configuration
        run: |
          statix check -i modules/hardware-configuration.nix

      - name: Check for dead code
        run: |
          deadnix . --exclude modules/hardware-configuration.nix
